countries = {
    'global': 'global',
    'andorra': 'ad',
    'argentina': 'ar',
    'austria': 'at',
    'australia': 'au',
    'belgium': 'be',
    'bulgaria': 'bg',
    'bolivia': 'bo',
    'brazil': 'br',
    'canada': 'ca',
    'switzerland': 'ch',
    'chile': 'cl',
    'colombia': 'co',
    'costa rica': 'cr',
    'cyprus': 'cy',
    'czech republic': 'cz',
    'germany': 'de',
    'denmark': 'dk',
    'dominican republic': 'do',
    'ecuador': 'ec',
    'estonia': 'ee',
    'spain': 'es',
    'finland': 'fi',
    'france': 'fr',
    'united kingdom': 'gb',
    'greece': 'gr',
    'guatemala': 'gt',
    'hong kong': 'hk',
    'honduras': 'hn',
    'hungary': 'hu',
    'indonesia': 'id',
    'ireland': 'ie',
    'israel': 'il',
    'iceland': 'is',
    'italy': 'it',
    'japan': 'jp',
    'lithuania': 'lt',
    'luxembourg': 'lu',
    'latvia': 'lv',
    'monaco': 'mc',
    'malta': 'mt',
    'mexico': 'mx',
    'malaysia': 'my',
    'nicaragua': 'ni',
    'netherlands': 'nl',
    'norway': 'no',
    'new zealand': 'nz',
    'panama': 'pa',
    'peru': 'pe',
    'philippines': 'ph',
    'poland': 'pl',
    'portugal': 'pt',
    'paraguay': 'py',
    'romania': 'ro',
    'sweden': 'se',
    'singapore': 'sg',
    'slovakia': 'sk',
    'el salvador': 'sv',
    'thailand': 'th',
    'turkey': 'tr',
    'taiwan': 'tw',
    'united states': 'us',
    'uruguay': 'uy',
    'vietnam': 'vn',
}
